/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlink from "./@chainlink";
export type { chainlink };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { AutomationBase } from "./@chainlink/contracts/src/v0.8/automation/AutomationBase";
export { AutomationBase__factory } from "./factories/@chainlink/contracts/src/v0.8/automation/AutomationBase__factory";
export type { AutomationCompatible } from "./@chainlink/contracts/src/v0.8/automation/AutomationCompatible";
export { AutomationCompatible__factory } from "./factories/@chainlink/contracts/src/v0.8/automation/AutomationCompatible__factory";
export type { AutomationCompatibleInterface } from "./@chainlink/contracts/src/v0.8/automation/interfaces/AutomationCompatibleInterface";
export { AutomationCompatibleInterface__factory } from "./factories/@chainlink/contracts/src/v0.8/automation/interfaces/AutomationCompatibleInterface__factory";
export type { HedgeAutomation } from "./contracts/HedgeAutomation";
export { HedgeAutomation__factory } from "./factories/contracts/HedgeAutomation__factory";
export type { IAutomationRegistry } from "./contracts/interfaces/IAutomationRegistry";
export { IAutomationRegistry__factory } from "./factories/contracts/interfaces/IAutomationRegistry__factory";
export type { IERC20 } from "./contracts/interfaces/IERC20";
export { IERC20__factory } from "./factories/contracts/interfaces/IERC20__factory";
