/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iAutomationRegistrySol from "./IAutomationRegistry.sol";
export { IERC20__factory } from "./IERC20__factory";
