#!/bin/bash

# RiskGuardian AI - PRECISE Avalanche Deployment
# Based on exact analysis of 36 .sol files

echo "🎯 RISKGUARDIAN AI - PRECISE AVALANCHE DEPLOYMENT"
echo "=================================================="
echo ""
echo "Based on analysis of your 36 .sol files:"
echo ""
echo "📦 CONTRACTS TO DEPLOY:"
echo "  ✅ 4  Core contracts       (ContractRegistry, RiskRegistry, etc.)"
echo "  ✅ 2  Automation contracts (AlertSystem, RiskGuardianMaster)"
echo "  ✅ 4  Hedging contracts    (StopLoss, Rebalance, Volatility, CrossChain)"
echo "  ✅ 1  Insurance contract   (RiskInsurance)"
echo "  ✅ 4+ Mock contracts       (SepoliaSetup + MockHedge + MockUniswap)"
echo "  ✅ 5+ Mock protocols       (Generated by SepoliaSetup)"
echo ""
echo "📚 LIBRARIES: Automatically linked (no deployment needed)"
echo "🔌 INTERFACES: Not deployed (used for compilation only)"
echo "📜 SCRIPTS: Not deployed (execution only)"
echo ""
echo "📊 TOTAL: ~15-20 contracts will be deployed"
echo ""

# Environment check
if [ ! -f .env ]; then
    echo "❌ ERROR: .env file not found"
    exit 1
fi

source .env

# Validate required environment variables
if [ -z "$PRIVATE_KEY" ]; then
    echo "❌ ERROR: PRIVATE_KEY not set in .env"
    exit 1
fi

if [ -z "$DEPLOYER_ADDRESS" ]; then
    echo "❌ ERROR: DEPLOYER_ADDRESS not set in .env"
    exit 1
fi

# Configuration
if [ -z "$AVALANCHE_FUJI_RPC" ]; then
    AVALANCHE_FUJI_RPC="https://api.avax-test.network/ext/bc/C/rpc"
fi

echo "⚙️  CONFIGURATION:"
echo "   Deployer: $DEPLOYER_ADDRESS"
echo "   Network: Avalanche Fuji Testnet"
echo "   RPC: $AVALANCHE_FUJI_RPC"
echo ""

# Validate wallet access
echo "🔐 Validating wallet access..."
WALLET_ADDRESS=$(cast wallet address --private-key $PRIVATE_KEY 2>/dev/null)
if [ "$WALLET_ADDRESS" != "$DEPLOYER_ADDRESS" ]; then
    echo "❌ ERROR: Private key does not match deployer address"
    echo "   Private key address: $WALLET_ADDRESS"
    echo "   Expected address: $DEPLOYER_ADDRESS"
    exit 1
fi
echo "✅ Wallet validation successful"
echo ""

# Balance check
BALANCE=$(cast balance $DEPLOYER_ADDRESS --rpc-url $AVALANCHE_FUJI_RPC)
BALANCE_ETH=$(cast from-wei $BALANCE)
echo "💰 Available AVAX: $BALANCE_ETH"

if (( $(echo "$BALANCE_ETH < 0.5" | bc -l) )); then
    echo "⚠️  Low balance. Get AVAX from: https://faucet.avax.network/"
    read -p "Continue? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo ""
echo "🚀 STARTING PRECISE DEPLOYMENT..."
echo ""

# Compile
echo "🔨 Compiling contracts..."
forge build

if [ $? -ne 0 ]; then
    echo "❌ Compilation failed"
    exit 1
fi

echo "✅ Compilation successful"
echo ""

# Deploy with private key explicitly passed
echo "📦 Deploying contracts..."

# First try with verification
echo "Attempting deployment with verification..."
forge script script/AvalanchePreciseDeploy.s.sol \
    --rpc-url $AVALANCHE_FUJI_RPC \
    --private-key $PRIVATE_KEY \
    --broadcast \
    --verify \
    --etherscan-api-key $SNOWTRACE_API_KEY \
    -vvv

DEPLOY_RESULT=$?

# If verification fails, try without verification
if [ $DEPLOY_RESULT -ne 0 ]; then
    echo ""
    echo "⚠️  Deployment with verification failed. Trying without verification..."
    echo ""
    
    forge script script/AvalanchePreciseDeploy.s.sol \
        --rpc-url $AVALANCHE_FUJI_RPC \
        --private-key $PRIVATE_KEY \
        --broadcast \
        -vvv
    
    DEPLOY_RESULT=$?
fi

if [ $DEPLOY_RESULT -eq 0 ]; then
    echo ""
    echo "✅ PRECISE DEPLOYMENT SUCCESSFUL!"
    echo ""
    echo "📋 CONTRACT SUMMARY:"
    echo "✓ All core contracts deployed"
    echo "✓ Automation system active"
    echo "✓ Hedging strategies ready"
    echo "✓ Insurance operational"
    echo "✓ Mock system configured (testnet)"
    echo ""
    echo "🔗 Verify contracts: https://testnet.snowtrace.io/"
    echo "�� Faucet: https://faucet.avax.network/"
    echo ""
    echo "📄 IMPORTANT: Save the contract addresses that appear in the logs above!"
    echo ""
    echo "🎉 RiskGuardian AI is live on Avalanche!"
else
    echo "❌ Deployment failed - check logs above"
    echo ""
    echo "🔧 TROUBLESHOOTING:"
    echo "1. Check if you have enough AVAX (need ~0.05 AVAX)"
    echo "2. Verify RPC is working: cast block-number --rpc-url $AVALANCHE_FUJI_RPC"
    echo "3. Check private key format (should start with 0x)"
    echo "4. Try running just the script without verification"
    exit 1
fi
