/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { HedgeAutomation__factory } from "./HedgeAutomation__factory";
