[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true 
test = "test"
cache_path = "cache"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# Remappings para dependências
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/"
]

# ===== RPC ENDPOINTS =====
[rpc_endpoints]
# Sepolia Testnet (Ethereum)
sepolia = "https://sepolia.drpc.org"
sepolia_alt = "https://ethereum-sepolia-rpc.publicnode.com"

# Providers secundários para Sepolia
#sepolia_alchemy = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
#sepolia_infura = "https://sepolia.infura.io/v3/${INFURA_PROJECT_ID}"
#sepolia_ankr = "https://rpc.ankr.com/eth_sepolia"

# Fallbacks
sepolia_1rpc = "https://1rpc.io/sepolia"
sepolia_blockpi = "https://ethereum-sepolia.blockpi.network/v1/rpc/public"

# Mainnet (para verificação)
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# Local development (comentado)
anvil = "http://localhost:8545"
localhost = "http://localhost:8545"

# Ronin Testnet (comentado)
# ronin_testnet = "https://saigon-testnet.roninchain.com/rpc"

# ===== ETHERSCAN CONFIG =====
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
#ronin_testnet = { key = "${RONIN_EXPLORER_API_KEY}", url = "https://api-saigon.roninchain.com/api" }

# Configuração de perfis
[profile.test]
verbosity = 2

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

# Configurações de formatação
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"