[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true 
test = "test"
cache_path = "cache"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# Remappings para dependências
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/"
]

# Configuração de RPC
[rpc_endpoints]
anvil = "http://localhost:8545"
localhost = "http://localhost:8545"

# Configuração Etherscan
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Configuração de perfis
[profile.test]
verbosity = 2

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

# Configurações de formatação
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"