/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAutomationRegistrySol from "./IAutomationRegistry.sol";
export type { iAutomationRegistrySol };
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export type { IAutomationRegistry } from "./IAutomationRegistry.sol/IAutomationRegistry";
export { IAutomationRegistry__factory } from "./factories/IAutomationRegistry.sol/IAutomationRegistry__factory";
export type { IERC20 } from "./IAutomationRegistry.sol/IERC20";
export { IERC20__factory } from "./factories/IAutomationRegistry.sol/IERC20__factory";
